service:
  name: aws-iam-access-key-rotation-enforcer

plugins:
  - serverless-webpack

custom:
  notificationEmailAddress: "jonathan.martin@pickr.works"

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "iam:ListUsers"
        - "iam:UpdateAccessKey"
        - "iam:ListAccessKeys"
        - "iam:GetAccessKeyLastUsed"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource: { "Fn::Join": [":", ["arn:aws:sns:${self:provider.region}", { "Ref": "AWS::AccountId" }, { "Fn::GetAtt": [ "AccessKeyRotationAlerts", TopicName ] } ] ]  }

functions:
  check:
    handler: handler.check
    events:
      - schedule: cron(15 10 ? * * *)
    environment:
      TOPIC_ARN: { "Fn::Join": [":", ["arn:aws:sns:${self:provider.region}", { "Ref": "AWS::AccountId" }, { "Fn::GetAtt": [ "AccessKeyRotationAlerts", TopicName ] } ] ]  }

resources:
  Resources:
    AccessKeyRotationAlerts:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: 'Access Key Rotation Alerts'
        TopicName: AccessKeyRotationAlerts
        Subscription:
        - Endpoint: ${self:custom.notificationEmailAddress}
          Protocol: email